### ISSUE TITLE
Missing dialout_prefixes causes problem in currently released gem 0.1.3, 

### ISSUE THREAD

**Issue by dytsai** [haberbyte/phoney#10]
You can reproduce it by

pn=PhoneNumber.new('1234567',:na)

undefined method `each' for nil:NilClass
/bundle/ruby/2.0.0/gems/phoney-0.1.3/lib/phoney/parser.rb:187:in`get_dialout_prefix'
/bundle/ruby/2.0.0/gems/phoney-0.1.3/lib/phoney/parser.rb:26:in `parse_to_parts'
/bundle/ruby/2.0.0/gems/phoney-0.1.3/lib/phoney/base.rb:43:in`initialize'

I noticed the entire project is under a complete rewrite and the issue seems to be resolved. Just wondering when you plan to release another new version?

Thanks,
Dan

**Comment by haberbyte** [comment]
API has changed, but this doesnt throw an error anymore with 0.2.x:

```
>> Phoney.region = :na
=> :na
>> Phoney.format("1234567")
=> "1234567"
```
