### ISSUE TITLE
uninitialized constant Phoney

### ISSUE THREAD

**Issue by craibuc** [haberbyte/phoney#15]
Version

``` bash
$ gem list phoney --details

*** LOCAL GEMS ***

phoney (0.1.3)
    Author: Jan Habermann
    Homepage: http://github.com/habermann24/phoney
    Installed at: /Users/craibuc/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0

    Ruby library that formats phone numbers.
```

IRB

``` ruby
irb(main):001:0> require 'phoney'
=> true
irb(main):002:0> pn = Phoney.new("+17041234567")
NameError: uninitialized constant Phoney
    from (irb):4
    from /Users/xxx/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
```

**Comment by rept** [comment]
Same issue, can somebody shed some light on this?

**Comment by haberbyte** [comment]
Oh I am sorry, this project has long been untouched and it seems there were a lot of changes that never were released to rubygems.

I just pushed a new version, but unfortunately this means it completely breaks the API and some features are missing.

But this should work with the 0.2.1 gem:
```
$ irb
>> require "phoney"
=> true
>> Phoney.format("+17041234567")
=> "+1 (704) 123-4567"
```

**Comment by rept** [comment]
Hi Jan, thanks for the speedy reply.  I noticed after my question the repo wasn't updated in a long time too.

**Comment by haberbyte** [comment]
Maybe https://github.com/daddyz/phonelib is a better go-to option for phone numbers right now.
